### ISSUE TITLE
Cannot get entry for stats

### ISSUE THREAD

**Issue by scottdangelo** [IBM/metrics-collector-service#37]
In the past, we could deploy to IBM Cloud and the repository would show up on the [stats page](https://metrics-tracker.mybluemix.net/stats) with a badge we could use, including a button.
I have deployed a [new repository](https://github.com/IBM/watson-stock-advisor) several times, but it does not show up on the stats page.
The changes to use metrics tracker are on the [addMetricsDeploy] (https://github.com/IBM/watson-stock-advisor/tree/addMetricsDeploy) branch.

**Comment by Tomcli** [comment]
Spacing is very crucial in the yaml file. It looks like your repository.yaml has too many spaces for indentation. You should use a 2 space tab when indenting the runtimes and services list.
```yaml
id: https://github.com/IBM/watson-stock-advisor
runtimes:
  - Cloud Foundry
services:
  - Discovery
  - Cloudant NoSQL DB
event_id: web
event_organizer: dev-journeys
language: nodejs
```
